@echo off
echo // automatically generated by generate_my_app_obj.bat > all_my_app.cpp

for %%c IN (..\mybilliard01\*.cpp) DO if NOT "%%c"=="..\mybilliard01\wWinMain.cpp" echo #include "%%c" >> all_my_app.cpp

