del MyCameraModeSMC_AutoGenerated.h MyCameraModeSMC_AutoGenerated.cpp
del MyCameraAimViewSMC_AutoGenerated.h MyCameraAimViewSMC_AutoGenerated.cpp
del MyCameraMoveViewMoveSMC_AutoGenerated.h MyCameraMoveViewMoveSMC_AutoGenerated.cpp
del MyCameraMoveViewRotateSMC_AutoGenerated.h MyCameraMoveViewRotateSMC_AutoGenerated.cpp
del MouseStateSMC_AutoGenerated.h MouseStateSMC_AutoGenerated.cpp
del MyCameraTopViewSMC_AutoGenerated.h MyCameraTopViewSMC_AutoGenerated.cpp

java -classpath ../smc.jar smc.Smc MyCameraModeSMC_AutoGenerated.smc
java -classpath ../smc.jar smc.Smc MyCameraAimViewSMC_AutoGenerated.smc
java -classpath ../smc.jar smc.Smc MyCameraMoveViewMoveSMC_AutoGenerated.smc
java -classpath ../smc.jar smc.Smc MyCameraMoveViewRotateSMC_AutoGenerated.smc
java -classpath ../smc.jar smc.Smc MouseStateSMC_AutoGenerated.smc
java -classpath ../smc.jar smc.Smc MyCameraTopViewSMC_AutoGenerated.smc
pause