#include "StdAfx.h"
#include "my_app.h"

#include "MyCameraModeSMC.h"
#include "MyCameraTopViewSMC.h"
#include "MyCameraAimViewSMC.h"
#include "MyCameraMoveViewMoveSMC.h"
#include "MyCameraMoveViewRotateSMC.h"
#include "MouseStateSMC.h"

#define _versID _versID_Mode
#include "MyCameraModeSMC_AutoGenerated.cpp"
#undef _versID

#define _versID _versID_TopView
#include "MyCameraTopViewSMC_AutoGenerated.cpp"
#undef _versID

#define _versID _versID_AimView
#include "MyCameraAimViewSMC_AutoGenerated.cpp"
#undef _versID

#define _versID _versID_MoveViewMove
#include "MyCameraMoveViewMoveSMC_AutoGenerated.cpp"
#undef _versID

#define _versID _versID_MoveViewRotate
#include "MyCameraMoveViewRotateSMC_AutoGenerated.cpp"
#undef _versID

#define _versID _versID_MouseState
#include "MouseStateSMC_AutoGenerated.cpp"
#undef _versID

