//----------------------------------------------
// MyCameraMoveViewMoveSMC_AutoGenerated.cpp
// FSM:       MyCameraMoveViewMoveSMC_AutoGenerated
// Context:   MyCameraMoveViewMoveSMC
// Version:   
// Generated: Sunday 08/30/2009 at 02:29:39 EDT
//


static char _versID[]  = "";

#include "MyCameraMoveViewMoveSMC_AutoGenerated.h"

namespace smc
{

//----------------------------------------------
// Definitions of static state objects

//----------------------------------------------
MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardState MyCameraMoveViewMoveSMC_AutoGenerated::MoveForward;
MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardLeftState MyCameraMoveViewMoveSMC_AutoGenerated::MoveBackwardLeft;
MyCameraMoveViewMoveSMC_AutoGeneratedMoveLeftState MyCameraMoveViewMoveSMC_AutoGenerated::MoveLeft;
MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardState MyCameraMoveViewMoveSMC_AutoGenerated::MoveBackward;
MyCameraMoveViewMoveSMC_AutoGeneratedMoveRightState MyCameraMoveViewMoveSMC_AutoGenerated::MoveRight;
MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardLeftState MyCameraMoveViewMoveSMC_AutoGenerated::MoveForwardLeft;
MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardRightState MyCameraMoveViewMoveSMC_AutoGenerated::MoveForwardRight;
MyCameraMoveViewMoveSMC_AutoGeneratedMoveStopState MyCameraMoveViewMoveSMC_AutoGenerated::MoveStop;
MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardRightState MyCameraMoveViewMoveSMC_AutoGenerated::MoveBackwardRight;

//----------------------------------------------
// Default Event Functions

//----------------------------------------------

void MyCameraMoveViewMoveSMC_AutoGeneratedState::beginMoveForward(MyCameraMoveViewMoveSMC_AutoGenerated& s)
  { s.FSMError("beginMoveForward", s.GetState().StateName()); }

void MyCameraMoveViewMoveSMC_AutoGeneratedState::endMoveLeft(MyCameraMoveViewMoveSMC_AutoGenerated& s)
  { s.FSMError("endMoveLeft", s.GetState().StateName()); }

void MyCameraMoveViewMoveSMC_AutoGeneratedState::endMoveBackward(MyCameraMoveViewMoveSMC_AutoGenerated& s)
  { s.FSMError("endMoveBackward", s.GetState().StateName()); }

void MyCameraMoveViewMoveSMC_AutoGeneratedState::beginMoveRight(MyCameraMoveViewMoveSMC_AutoGenerated& s)
  { s.FSMError("beginMoveRight", s.GetState().StateName()); }

void MyCameraMoveViewMoveSMC_AutoGeneratedState::beginMoveBackward(MyCameraMoveViewMoveSMC_AutoGenerated& s)
  { s.FSMError("beginMoveBackward", s.GetState().StateName()); }

void MyCameraMoveViewMoveSMC_AutoGeneratedState::beginMoveLeft(MyCameraMoveViewMoveSMC_AutoGenerated& s)
  { s.FSMError("beginMoveLeft", s.GetState().StateName()); }

void MyCameraMoveViewMoveSMC_AutoGeneratedState::endMoveRight(MyCameraMoveViewMoveSMC_AutoGenerated& s)
  { s.FSMError("endMoveRight", s.GetState().StateName()); }

void MyCameraMoveViewMoveSMC_AutoGeneratedState::endMoveForward(MyCameraMoveViewMoveSMC_AutoGenerated& s)
  { s.FSMError("endMoveForward", s.GetState().StateName()); }

//----------------------------------------------
// The States and their Transitions
//----------------------------------------------

//----------------------------------------------
// MoveForward Actions and Transitions
//----------------------------------------------

// Starting State: MoveForward
// Event:          endMoveForward
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardState::endMoveForward( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.endMoveForward_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveStop);

    // Entry functions for: MoveStop
    s.entryMoveStop_();
}

// Starting State: MoveForward
// Event:          beginMoveRight
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardState::beginMoveRight( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.beginMoveRight_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveForwardRight);
}

// Starting State: MoveForward
// Event:          beginMoveLeft
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardState::beginMoveLeft( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.beginMoveLeft_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveForwardLeft);
}

//----------------------------------------------
// MoveBackwardLeft Actions and Transitions
//----------------------------------------------

// Starting State: MoveBackwardLeft
// Event:          endMoveLeft
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardLeftState::endMoveLeft( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.endMoveLeft_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveBackward);
}

// Starting State: MoveBackwardLeft
// Event:          endMoveBackward
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardLeftState::endMoveBackward( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.endMoveBackward_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveLeft);
}

//----------------------------------------------
// MoveLeft Actions and Transitions
//----------------------------------------------

// Starting State: MoveLeft
// Event:          beginMoveBackward
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveLeftState::beginMoveBackward( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.beginMoveBackward_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveBackwardLeft);
}

// Starting State: MoveLeft
// Event:          beginMoveForward
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveLeftState::beginMoveForward( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.beginMoveForward_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveForwardLeft);
}

// Starting State: MoveLeft
// Event:          endMoveLeft
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveLeftState::endMoveLeft( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.endMoveLeft_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveStop);

    // Entry functions for: MoveStop
    s.entryMoveStop_();
}

//----------------------------------------------
// MoveBackward Actions and Transitions
//----------------------------------------------

// Starting State: MoveBackward
// Event:          beginMoveLeft
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardState::beginMoveLeft( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.beginMoveLeft_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveBackwardLeft);
}

// Starting State: MoveBackward
// Event:          beginMoveRight
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardState::beginMoveRight( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.beginMoveRight_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveBackwardRight);
}

// Starting State: MoveBackward
// Event:          endMoveBackward
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardState::endMoveBackward( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.endMoveBackward_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveStop);

    // Entry functions for: MoveStop
    s.entryMoveStop_();
}

//----------------------------------------------
// MoveRight Actions and Transitions
//----------------------------------------------

// Starting State: MoveRight
// Event:          beginMoveForward
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveRightState::beginMoveForward( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.beginMoveForward_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveForwardRight);
}

// Starting State: MoveRight
// Event:          endMoveRight
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveRightState::endMoveRight( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.endMoveRight_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveStop);

    // Entry functions for: MoveStop
    s.entryMoveStop_();
}

// Starting State: MoveRight
// Event:          beginMoveBackward
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveRightState::beginMoveBackward( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.beginMoveBackward_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveBackwardRight);
}

//----------------------------------------------
// MoveForwardLeft Actions and Transitions
//----------------------------------------------

// Starting State: MoveForwardLeft
// Event:          endMoveLeft
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardLeftState::endMoveLeft( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.endMoveLeft_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveForward);
}

// Starting State: MoveForwardLeft
// Event:          endMoveForward
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardLeftState::endMoveForward( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.endMoveForward_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveLeft);
}

//----------------------------------------------
// MoveForwardRight Actions and Transitions
//----------------------------------------------

// Starting State: MoveForwardRight
// Event:          endMoveRight
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardRightState::endMoveRight( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.endMoveRight_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveForward);
}

// Starting State: MoveForwardRight
// Event:          endMoveForward
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardRightState::endMoveForward( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.endMoveForward_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveRight);
}

//----------------------------------------------
// MoveStop Actions and Transitions
//----------------------------------------------

// Starting State: MoveStop
// Event:          beginMoveBackward
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveStopState::beginMoveBackward( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.beginMoveBackward_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveBackward);
}

// Starting State: MoveStop
// Event:          beginMoveLeft
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveStopState::beginMoveLeft( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.beginMoveLeft_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveLeft);
}

// Starting State: MoveStop
// Event:          beginMoveRight
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveStopState::beginMoveRight( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.beginMoveRight_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveRight);
}

// Starting State: MoveStop
// Event:          beginMoveForward
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveStopState::beginMoveForward( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.beginMoveForward_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveForward);
}

//----------------------------------------------
// MoveBackwardRight Actions and Transitions
//----------------------------------------------

// Starting State: MoveBackwardRight
// Event:          endMoveRight
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardRightState::endMoveRight( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.endMoveRight_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveBackward);
}

// Starting State: MoveBackwardRight
// Event:          endMoveBackward
//
void MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardRightState::endMoveBackward( MyCameraMoveViewMoveSMC_AutoGenerated& s )
{

    s.endMoveBackward_();

    // Change the state
    s.SetState(MyCameraMoveViewMoveSMC_AutoGenerated::MoveRight);
}

//----------------------------------------------
// State Machine Constructor: MyCameraMoveViewMoveSMC_AutoGenerated
//  set Initial State to: MoveStop
//
//----------------------------------------------
MyCameraMoveViewMoveSMC_AutoGenerated::MyCameraMoveViewMoveSMC_AutoGenerated() : itsState(&MoveStop)
{
    // Entry functions for: MoveStop
    entryMoveStop_();
}

//  Get version information
//
const char* MyCameraMoveViewMoveSMC_AutoGenerated::GetVersion() const
{ return _versID; }

}  // end namespace smc

