#ifndef FSM_MouseStateSMC_AutoGenerated_08_30_2009_02_29_40_H
#define FSM_MouseStateSMC_AutoGenerated_08_30_2009_02_29_40_H
//----------------------------------------------
// MouseStateSMC_AutoGenerated.h
// FSM:       MouseStateSMC_AutoGenerated
// Context:   MouseStateSMC
// Version:   
// Generated: Sunday 08/30/2009 at 02:29:40 EDT
//


// Included header files

#include "MouseStateSMC_AutoGenerated.h"

namespace smc
{

// Forward Declarations

class MouseStateSMC_AutoGenerated;

//----------------------------------------------
// MouseStateSMC_AutoGeneratedState: The base state class
//----------------------------------------------
class MouseStateSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const = 0;
    virtual void captureReleased( MouseStateSMC_AutoGenerated& );
    virtual void buttonDown( MouseStateSMC_AutoGenerated& );
    virtual void buttonUp( MouseStateSMC_AutoGenerated& );
    virtual void move( MouseStateSMC_AutoGenerated& );
};

//----------------------------------------------
// State: MouseReady
//----------------------------------------------
class MouseStateSMC_AutoGeneratedMouseReadyState : public MouseStateSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "MouseReady"; }
    virtual void captureReleased( MouseStateSMC_AutoGenerated& );
    virtual void buttonDown( MouseStateSMC_AutoGenerated& );
    virtual void move( MouseStateSMC_AutoGenerated& );
};
//----------------------------------------------
// State: ButtonDown
//----------------------------------------------
class MouseStateSMC_AutoGeneratedButtonDownState : public MouseStateSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "ButtonDown"; }
    virtual void captureReleased( MouseStateSMC_AutoGenerated& );
    virtual void buttonUp( MouseStateSMC_AutoGenerated& );
    virtual void move( MouseStateSMC_AutoGenerated& );
};
//----------------------------------------------
// State: Drag
//----------------------------------------------
class MouseStateSMC_AutoGeneratedDragState : public MouseStateSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "Drag"; }
    virtual void captureReleased( MouseStateSMC_AutoGenerated& );
    virtual void buttonUp( MouseStateSMC_AutoGenerated& );
    virtual void move( MouseStateSMC_AutoGenerated& );
};
//----------------------------------------------
// MouseStateSMC_AutoGenerated: The Finite State Machine class
//----------------------------------------------
class MouseStateSMC_AutoGenerated: public MouseStateSMC
{
  public: 
    // Static State variables
    static MouseStateSMC_AutoGeneratedMouseReadyState MouseReady;
    static MouseStateSMC_AutoGeneratedButtonDownState ButtonDown;
    static MouseStateSMC_AutoGeneratedDragState Drag;

    MouseStateSMC_AutoGenerated(); // default Constructor

    // Event functions
    virtual void captureReleased() { itsState->captureReleased( *this ); }
    virtual void buttonDown() { itsState->buttonDown( *this ); }
    virtual void buttonUp() { itsState->buttonUp( *this ); }
    virtual void move() { itsState->move( *this ); }

    // State Accessor functions
    void SetState( MouseStateSMC_AutoGeneratedState& theState ) { itsState = &theState; }
    MouseStateSMC_AutoGeneratedState& GetState() const { return *itsState; }

    const char* GetCurrentStateName() const { return itsState->StateName(); }
    const char* GetVersion() const;

  private: 
    MouseStateSMC_AutoGeneratedState* itsState;
};

}  // end namespace smc

#endif /* FSM_MouseStateSMC_AutoGenerated_08_30_2009_02_29_40_H */
