#ifndef FSM_MyCameraAimViewSMC_AutoGenerated_08_30_2009_02_29_39_H
#define FSM_MyCameraAimViewSMC_AutoGenerated_08_30_2009_02_29_39_H
//----------------------------------------------
// MyCameraAimViewSMC_AutoGenerated.h
// FSM:       MyCameraAimViewSMC_AutoGenerated
// Context:   MyCameraAimViewSMC
// Version:   
// Generated: Sunday 08/30/2009 at 02:29:39 EDT
//


// Included header files

#include "MyCameraAimViewSMC_AutoGenerated.h"

namespace smc
{

// Forward Declarations

class MyCameraAimViewSMC_AutoGenerated;

//----------------------------------------------
// MyCameraAimViewSMC_AutoGeneratedState: The base state class
//----------------------------------------------
class MyCameraAimViewSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const = 0;
    virtual void endAimLeft( MyCameraAimViewSMC_AutoGenerated& );
    virtual void beginAimLeft( MyCameraAimViewSMC_AutoGenerated& );
    virtual void endAimRight( MyCameraAimViewSMC_AutoGenerated& );
    virtual void beginShoot( MyCameraAimViewSMC_AutoGenerated& );
    virtual void beginAimRight( MyCameraAimViewSMC_AutoGenerated& );
    virtual void endShoot( MyCameraAimViewSMC_AutoGenerated& );
};

//----------------------------------------------
// State: AimRight
//----------------------------------------------
class MyCameraAimViewSMC_AutoGeneratedAimRightState : public MyCameraAimViewSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "AimRight"; }
    virtual void endAimRight( MyCameraAimViewSMC_AutoGenerated& );
};
//----------------------------------------------
// State: AimStop
//----------------------------------------------
class MyCameraAimViewSMC_AutoGeneratedAimStopState : public MyCameraAimViewSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "AimStop"; }
    virtual void beginAimRight( MyCameraAimViewSMC_AutoGenerated& );
    virtual void beginShoot( MyCameraAimViewSMC_AutoGenerated& );
    virtual void beginAimLeft( MyCameraAimViewSMC_AutoGenerated& );
};
//----------------------------------------------
// State: AimLeft
//----------------------------------------------
class MyCameraAimViewSMC_AutoGeneratedAimLeftState : public MyCameraAimViewSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "AimLeft"; }
    virtual void endAimLeft( MyCameraAimViewSMC_AutoGenerated& );
};
//----------------------------------------------
// State: Shoot
//----------------------------------------------
class MyCameraAimViewSMC_AutoGeneratedShootState : public MyCameraAimViewSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "Shoot"; }
    virtual void endShoot( MyCameraAimViewSMC_AutoGenerated& );
};
//----------------------------------------------
// MyCameraAimViewSMC_AutoGenerated: The Finite State Machine class
//----------------------------------------------
class MyCameraAimViewSMC_AutoGenerated: public MyCameraAimViewSMC
{
  public: 
    // Static State variables
    static MyCameraAimViewSMC_AutoGeneratedAimRightState AimRight;
    static MyCameraAimViewSMC_AutoGeneratedAimStopState AimStop;
    static MyCameraAimViewSMC_AutoGeneratedAimLeftState AimLeft;
    static MyCameraAimViewSMC_AutoGeneratedShootState Shoot;

    MyCameraAimViewSMC_AutoGenerated(); // default Constructor

    // Event functions
    virtual void endAimLeft() { itsState->endAimLeft( *this ); }
    virtual void beginAimLeft() { itsState->beginAimLeft( *this ); }
    virtual void endAimRight() { itsState->endAimRight( *this ); }
    virtual void beginShoot() { itsState->beginShoot( *this ); }
    virtual void beginAimRight() { itsState->beginAimRight( *this ); }
    virtual void endShoot() { itsState->endShoot( *this ); }

    // State Accessor functions
    void SetState( MyCameraAimViewSMC_AutoGeneratedState& theState ) { itsState = &theState; }
    MyCameraAimViewSMC_AutoGeneratedState& GetState() const { return *itsState; }

    const char* GetCurrentStateName() const { return itsState->StateName(); }
    const char* GetVersion() const;

  private: 
    MyCameraAimViewSMC_AutoGeneratedState* itsState;
};

}  // end namespace smc

#endif /* FSM_MyCameraAimViewSMC_AutoGenerated_08_30_2009_02_29_39_H */
