#ifndef FSM_MyCameraMoveViewMoveSMC_AutoGenerated_08_30_2009_02_29_39_H
#define FSM_MyCameraMoveViewMoveSMC_AutoGenerated_08_30_2009_02_29_39_H
//----------------------------------------------
// MyCameraMoveViewMoveSMC_AutoGenerated.h
// FSM:       MyCameraMoveViewMoveSMC_AutoGenerated
// Context:   MyCameraMoveViewMoveSMC
// Version:   
// Generated: Sunday 08/30/2009 at 02:29:39 EDT
//


// Included header files

#include "MyCameraMoveViewMoveSMC_AutoGenerated.h"

namespace smc
{

// Forward Declarations

class MyCameraMoveViewMoveSMC_AutoGenerated;

//----------------------------------------------
// MyCameraMoveViewMoveSMC_AutoGeneratedState: The base state class
//----------------------------------------------
class MyCameraMoveViewMoveSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const = 0;
    virtual void beginMoveForward( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void endMoveLeft( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void endMoveBackward( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void beginMoveRight( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void beginMoveBackward( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void beginMoveLeft( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void endMoveRight( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void endMoveForward( MyCameraMoveViewMoveSMC_AutoGenerated& );
};

//----------------------------------------------
// State: MoveForward
//----------------------------------------------
class MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardState : public MyCameraMoveViewMoveSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "MoveForward"; }
    virtual void endMoveForward( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void beginMoveRight( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void beginMoveLeft( MyCameraMoveViewMoveSMC_AutoGenerated& );
};
//----------------------------------------------
// State: MoveBackwardLeft
//----------------------------------------------
class MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardLeftState : public MyCameraMoveViewMoveSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "MoveBackwardLeft"; }
    virtual void endMoveLeft( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void endMoveBackward( MyCameraMoveViewMoveSMC_AutoGenerated& );
};
//----------------------------------------------
// State: MoveLeft
//----------------------------------------------
class MyCameraMoveViewMoveSMC_AutoGeneratedMoveLeftState : public MyCameraMoveViewMoveSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "MoveLeft"; }
    virtual void beginMoveBackward( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void beginMoveForward( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void endMoveLeft( MyCameraMoveViewMoveSMC_AutoGenerated& );
};
//----------------------------------------------
// State: MoveBackward
//----------------------------------------------
class MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardState : public MyCameraMoveViewMoveSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "MoveBackward"; }
    virtual void beginMoveLeft( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void beginMoveRight( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void endMoveBackward( MyCameraMoveViewMoveSMC_AutoGenerated& );
};
//----------------------------------------------
// State: MoveRight
//----------------------------------------------
class MyCameraMoveViewMoveSMC_AutoGeneratedMoveRightState : public MyCameraMoveViewMoveSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "MoveRight"; }
    virtual void beginMoveForward( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void endMoveRight( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void beginMoveBackward( MyCameraMoveViewMoveSMC_AutoGenerated& );
};
//----------------------------------------------
// State: MoveForwardLeft
//----------------------------------------------
class MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardLeftState : public MyCameraMoveViewMoveSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "MoveForwardLeft"; }
    virtual void endMoveLeft( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void endMoveForward( MyCameraMoveViewMoveSMC_AutoGenerated& );
};
//----------------------------------------------
// State: MoveForwardRight
//----------------------------------------------
class MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardRightState : public MyCameraMoveViewMoveSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "MoveForwardRight"; }
    virtual void endMoveRight( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void endMoveForward( MyCameraMoveViewMoveSMC_AutoGenerated& );
};
//----------------------------------------------
// State: MoveStop
//----------------------------------------------
class MyCameraMoveViewMoveSMC_AutoGeneratedMoveStopState : public MyCameraMoveViewMoveSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "MoveStop"; }
    virtual void beginMoveBackward( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void beginMoveLeft( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void beginMoveRight( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void beginMoveForward( MyCameraMoveViewMoveSMC_AutoGenerated& );
};
//----------------------------------------------
// State: MoveBackwardRight
//----------------------------------------------
class MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardRightState : public MyCameraMoveViewMoveSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "MoveBackwardRight"; }
    virtual void endMoveRight( MyCameraMoveViewMoveSMC_AutoGenerated& );
    virtual void endMoveBackward( MyCameraMoveViewMoveSMC_AutoGenerated& );
};
//----------------------------------------------
// MyCameraMoveViewMoveSMC_AutoGenerated: The Finite State Machine class
//----------------------------------------------
class MyCameraMoveViewMoveSMC_AutoGenerated: public MyCameraMoveViewMoveSMC
{
  public: 
    // Static State variables
    static MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardState MoveForward;
    static MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardLeftState MoveBackwardLeft;
    static MyCameraMoveViewMoveSMC_AutoGeneratedMoveLeftState MoveLeft;
    static MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardState MoveBackward;
    static MyCameraMoveViewMoveSMC_AutoGeneratedMoveRightState MoveRight;
    static MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardLeftState MoveForwardLeft;
    static MyCameraMoveViewMoveSMC_AutoGeneratedMoveForwardRightState MoveForwardRight;
    static MyCameraMoveViewMoveSMC_AutoGeneratedMoveStopState MoveStop;
    static MyCameraMoveViewMoveSMC_AutoGeneratedMoveBackwardRightState MoveBackwardRight;

    MyCameraMoveViewMoveSMC_AutoGenerated(); // default Constructor

    // Event functions
    virtual void beginMoveForward() { itsState->beginMoveForward( *this ); }
    virtual void endMoveLeft() { itsState->endMoveLeft( *this ); }
    virtual void endMoveBackward() { itsState->endMoveBackward( *this ); }
    virtual void beginMoveRight() { itsState->beginMoveRight( *this ); }
    virtual void beginMoveBackward() { itsState->beginMoveBackward( *this ); }
    virtual void beginMoveLeft() { itsState->beginMoveLeft( *this ); }
    virtual void endMoveRight() { itsState->endMoveRight( *this ); }
    virtual void endMoveForward() { itsState->endMoveForward( *this ); }

    // State Accessor functions
    void SetState( MyCameraMoveViewMoveSMC_AutoGeneratedState& theState ) { itsState = &theState; }
    MyCameraMoveViewMoveSMC_AutoGeneratedState& GetState() const { return *itsState; }

    const char* GetCurrentStateName() const { return itsState->StateName(); }
    const char* GetVersion() const;

  private: 
    MyCameraMoveViewMoveSMC_AutoGeneratedState* itsState;
};

}  // end namespace smc

#endif /* FSM_MyCameraMoveViewMoveSMC_AutoGenerated_08_30_2009_02_29_39_H */
