#ifndef FSM_MyCameraTopViewSMC_AutoGenerated_08_30_2009_02_29_40_H
#define FSM_MyCameraTopViewSMC_AutoGenerated_08_30_2009_02_29_40_H
//----------------------------------------------
// MyCameraTopViewSMC_AutoGenerated.h
// FSM:       MyCameraTopViewSMC_AutoGenerated
// Context:   MyCameraTopViewSMC
// Version:   
// Generated: Sunday 08/30/2009 at 02:29:40 EDT
//


// Included header files

#include "MyCameraTopViewSMC_AutoGenerated.h"

namespace smc
{

// Forward Declarations

class MyCameraTopViewSMC_AutoGenerated;

//----------------------------------------------
// MyCameraTopViewSMC_AutoGeneratedState: The base state class
//----------------------------------------------
class MyCameraTopViewSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const = 0;
    virtual void beginRotateLeft( MyCameraTopViewSMC_AutoGenerated& );
    virtual void beginRotateRight( MyCameraTopViewSMC_AutoGenerated& );
    virtual void endRotateLeft( MyCameraTopViewSMC_AutoGenerated& );
    virtual void endRotateRight( MyCameraTopViewSMC_AutoGenerated& );
};

//----------------------------------------------
// State: RotateRight
//----------------------------------------------
class MyCameraTopViewSMC_AutoGeneratedRotateRightState : public MyCameraTopViewSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "RotateRight"; }
    virtual void endRotateRight( MyCameraTopViewSMC_AutoGenerated& );
};
//----------------------------------------------
// State: RotateStop
//----------------------------------------------
class MyCameraTopViewSMC_AutoGeneratedRotateStopState : public MyCameraTopViewSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "RotateStop"; }
    virtual void beginRotateRight( MyCameraTopViewSMC_AutoGenerated& );
    virtual void beginRotateLeft( MyCameraTopViewSMC_AutoGenerated& );
};
//----------------------------------------------
// State: RotateLeft
//----------------------------------------------
class MyCameraTopViewSMC_AutoGeneratedRotateLeftState : public MyCameraTopViewSMC_AutoGeneratedState
{
  public: 
    virtual const char* StateName() const
        { return "RotateLeft"; }
    virtual void endRotateLeft( MyCameraTopViewSMC_AutoGenerated& );
};
//----------------------------------------------
// MyCameraTopViewSMC_AutoGenerated: The Finite State Machine class
//----------------------------------------------
class MyCameraTopViewSMC_AutoGenerated: public MyCameraTopViewSMC
{
  public: 
    // Static State variables
    static MyCameraTopViewSMC_AutoGeneratedRotateRightState RotateRight;
    static MyCameraTopViewSMC_AutoGeneratedRotateStopState RotateStop;
    static MyCameraTopViewSMC_AutoGeneratedRotateLeftState RotateLeft;

    MyCameraTopViewSMC_AutoGenerated(); // default Constructor

    // Event functions
    virtual void beginRotateLeft() { itsState->beginRotateLeft( *this ); }
    virtual void beginRotateRight() { itsState->beginRotateRight( *this ); }
    virtual void endRotateLeft() { itsState->endRotateLeft( *this ); }
    virtual void endRotateRight() { itsState->endRotateRight( *this ); }

    // State Accessor functions
    void SetState( MyCameraTopViewSMC_AutoGeneratedState& theState ) { itsState = &theState; }
    MyCameraTopViewSMC_AutoGeneratedState& GetState() const { return *itsState; }

    const char* GetCurrentStateName() const { return itsState->StateName(); }
    const char* GetVersion() const;

  private: 
    MyCameraTopViewSMC_AutoGeneratedState* itsState;
};

}  // end namespace smc

#endif /* FSM_MyCameraTopViewSMC_AutoGenerated_08_30_2009_02_29_40_H */
